apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pizza-apiserver
  namespace: pizza-apiserver
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels: 
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: pizza-apiserver
        image: docker.io/jackyzhangfd/kube-pizza-apiserver:0.0.1
        imagePullPolicy: Always
        args: ["--etcd-servers=http://localhost:2379"]
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.1