apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregated-apiserver-clusterrole
rules:
- apiGroups: [""]
  resources: ["namespaces"]
    verbs: ["get", "watch","list"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutationwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["get","watch", "list"]