apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.autobusi.group.pizza.restaurant
spec:
  insecureSkipTLSVerify: true
  group: autobusi.group.pizza.restaurant
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: pizza-apiserver
  version: v1alpha1